services:
  yocto-docker-container:
    image: yocto-docker-image

    tty: true
    stdin_open: true
    user: yocto

    volumes:
      - /home/amirhossein/Github/worktree-walnascar-rauc-qt6-glfs:/opt/yocto-docker
      #- /home/amirhossein/Projects/yocto-sdk:/opt/yocto-sdk
      - /home/amirhossein/Github/worktee-walnascar-eglfs/build:/opt/yocto-docker/build
      - /home/amirhossein/tmp/yocto/build/downloads:/opt/yocto-docker/build/downloads

    deploy:
      resources:
        limits:
          memory: 17g
    memswap_limit: 17g
