
require conf/distro/poky.conf

DISTRO = "simple-framebuffer"
DISTRO_NAME = "Simple framebuffer distro"

EXTRA_IMAGE_FEATURES:remove = " debug-tweaks"
EXTRA_IMAGE_FEATURES:append = " allow-root-login"

ROOT_PASSWD = "\$6\$EcrQCmc4FC8oY8Gu\$MNtBPD8mOktVleWl.J69hFza.KfW2v4VBH7hMzgDATYCQJpBI1YWlFxoBeL.IqwkcSqGYMAojDzFPsh9GJJC4/"

INHERIT += "extrausers"
EXTRA_USERS_PARAMS = "usermod -p '${ROOT_PASSWD}' root;"

# Import common HDMI config
require conf/distro/common-hdmi.inc
