require conf/distro/poky.conf

DISTRO = "simple-desktop"
DISTRO_NAME = "Simple Desktop"

EXTRA_IMAGE_FEATURES:remove = " debug-tweaks"
EXTRA_IMAGE_FEATURES:append = " allow-root-login"

ROOT_PASSWD = "\$6\$EcrQCmc4FC8oY8Gu\$MNtBPD8mOktVleWl.J69hFza.KfW2v4VBH7hMzgDATYCQJpBI1YWlFxoBeL.IqwkcSqGYMAojDzFPsh9GJJC4/"

INHERIT += "extrausers"
EXTRA_USERS_PARAMS = "usermod -p '${ROOT_PASSWD}' root;"

DISTRO_FEATURES:append = " wayland pam usrmerge"
PREFERRED_PROVIDER_virtual/mesa = "mesa"
PREFERRED_PROVIDER_virtual/libgl = "mesa"
PREFERRED_PROVIDER_virtual/libgles1 = "mesa"
PREFERRED_PROVIDER_virtual/libgles2 = "mesa"
PREFERRED_PROVIDER_virtual/egl = "mesa"

# Enable VC4 graphics driver
ENABLE_DWC2_HOST = "1"
ENABLE_UART = "1"
GPU_MEM = "128"

# Enable systemd
DISTRO_FEATURES:append = " systemd"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
# Optional: Remove sysvinit if you want pure systemd
DISTRO_FEATURES_BACKFILL_CONSIDERED:append = " sysvinit"

IMAGE_INSTALL:append = " \
    virtual-keyboard \
    evtest \
    libsdl3 \
    uart-text-viewer \
    "

PACKAGECONFIG:append:pn-sdl3 = " wayland"


# RPI_EXTRA_CONFIG = "dtoverlay=uart-echo-overlay"
# KERNEL_DEVICETREE:append = " overlays/uart-echo-overlay.dtbo"
# IMAGE_INSTALL:append = " uart-echo-overlay"

# IMAGE_INSTALL:append = " my-dtbo"


# RPI_KERNEL_DEVICETREE_OVERLAYS += "overlays/uart-echo-overlay.dtbo"



# IMAGE_INSTALL:append = " my-boot-files"

# RPI_KERNEL_DEVICETREE_OVERLAYS += "overlays/very-special-file.dtbo "