
require conf/distro/poky.conf

DISTRO = "simple-framebuffer"
DISTRO_NAME = "Simple framebuffer distro"

EXTRA_IMAGE_FEATURES:remove = " debug-tweaks"
EXTRA_IMAGE_FEATURES:append = " allow-root-login"

ROOT_PASSWD = "\$6\$EcrQCmc4FC8oY8Gu\$MNtBPD8mOktVleWl.J69hFza.KfW2v4VBH7hMzgDATYCQJpBI1YWlFxoBeL.IqwkcSqGYMAojDzFPsh9GJJC4/"

INHERIT += "extrausers"
EXTRA_USERS_PARAMS = "usermod -p '${ROOT_PASSWD}' root;"

# Common HDMI config
DISABLE_OVERSCAN = "1"
GPU_MEM = "128"
HDMI_DRIVE = "2"
CONFIG_HDMI_BOOST = "4"
HDMI_FORCE_HOTPLUG = "1"

RPI_EXTRA_CONFIG = " \n\
hdmi_safe=1 \n\
"

CMDLINE:append = " video=HDMI-A-1:1920x1080M@60D"