# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-uartkbd"
BBFILE_PATTERN_meta-uartkbd = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-uartkbd = "6"

LAYERDEPENDS_meta-uartkbd = "core"
LAYERSERIES_COMPAT_meta-uartkbd = "scarthgap"
