require conf/distro/poky.conf

DISTRO = "distro-eglfs"
DISTRO_NAME = "eglfs distro"

INHERIT += "extrausers"
RAW_PASSWORD = "pi"
# PASSWD_ROOT="$(printf '%q' $(mkpasswd -m sha256crypt ${RAW_PASSWORD}))"
PASSWD_ROOT="$(printf '${RAW_PASSWORD}' | openssl passwd -6 -stdin)"
EXTRA_USERS_PARAMS = " usermod -p '${PASSWD_ROOT}' root; "

DISTRO_FEATURES:remove = "x11 wayland"
DISTRO_FEATURES:append = " opengl kms drm udev eglkms pam"
VIRTUAL-RUNTIME_dev_manager = "udev"


# Add GPU support for RPi5
MACHINE_FEATURES:append = " vc4graphics"

# Raspberry Pi GPU memory
GPU_MEM = "128"

# Enable proper graphics drivers
ENABLE_UART = "1"