require conf/distro/poky.conf

DISTRO = "distro-eglfs"
DISTRO_NAME = "eglfs distro"

INHERIT += "extrausers"
RAW_PASSWORD = "pi"
PASSWD_ROOT="$(printf '${RAW_PASSWORD}' | openssl passwd -6 -stdin)"
EXTRA_USERS_PARAMS = " usermod -p '${PASSWD_ROOT}' root; "

DISTRO_FEATURES:remove = "x11 wayland"
DISTRO_FEATURES:append = " opengl kms drm udev eglkms pam"
VIRTUAL-RUNTIME_dev_manager = "udev"


# Switch from systemd to sysvinit
INIT_MANAGER = "sysvinit"
#VIRTUAL-RUNTIME_init_manager = "sysvinit"

# Enable D-Bus
DISTRO_FEATURES += "dbus"

# Add D-Bus to your image
IMAGE_INSTALL += "dbus"
IMAGE_INSTALL += "dbus-glib-dev glib-2.0-dev rauc-dbus-client eudev"


# Add GPU support for RPi5
MACHINE_FEATURES:append = " vc4graphics"

# Raspberry Pi GPU memory
GPU_MEM = "128"

# Enable proper graphics drivers
ENABLE_UART = "1"

# RAUC

ENABLE_UART = "1"
RPI_USE_U_BOOT = "1"
PREFERRED_VERSION_linux-raspberrypi = "6.12.%"
WKS_FILE = "mywic.wks"
#WKS_FILE = "sdimage-dual-raspberrypi.wks.in"
IMAGE_INSTALL:append = " u-boot-fw-utils u-boot-tools"
IMAGE_INSTALL:append = " kernel-modules raspi-utils"

IMAGE_INSTALL:append = " e2fsprogs"
IMAGE_INSTALL:append = " rauc rauc-hawkbit-updater" 
DISTRO_FEATURES:append = " rauc"
IMAGE_FSTYPES:append = " ext4"

IMAGE_INSTALL:append = " rauc-mark-good rauc-service"
